// Loads .env into process.env. Must be the FIRST import: AppModule reads
// process.env.ARCJET_KEY while it is being defined, which happens as soon as
// the import below is evaluated.
import 'dotenv/config';

import express from 'express';
import { BadRequestException, ValidationPipe } from '@nestjs/common';
import { NestFactory, Reflector } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { toNodeHandler } from 'better-auth/node';
import { AppModule } from './app.module.js';
import { auth } from './auth/auth.js';
import { ResponseInterceptor } from './common/response.interceptor.js';

async function bootstrap() {
  // Better Auth needs the raw, unparsed request body, so Nest's automatic
  // body parser is disabled here and re-enabled below for every other
  // route. This is a global switch, not one scoped to /api/auth, so it has
  // to happen at this level rather than per controller.
  const app = await NestFactory.create(AppModule, { bodyParser: false });
  const expressApp = app.getHttpAdapter().getInstance();

  // Wraps every successful Nest controller response in { statusCode,
  // message, data }. Built manually (not an APP_INTERCEPTOR provider) so it
  // can pull the Reflector straight from the app container, per Nest's own
  // pattern for a global interceptor that needs DI outside a module.
  app.useGlobalInterceptors(new ResponseInterceptor(app.get(Reflector)));

  // Turns class-validator's per-property errors into a flat
  // { property, message } array instead of Nest's default nested
  // ValidationError[] shape, so clients get one predictable format.
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      transform: true,
      exceptionFactory: (errors) =>
        new BadRequestException(
          errors.flatMap((error) =>
            Object.values(error.constraints ?? {}).map((message) => ({
              property: error.property,
              message,
            })),
          ),
        ),
    }),
  );

  // Registered as a direct Express route (not app.use(prefix, ...)), so
  // req.url stays the full path; app.use() would strip the mount prefix,
  // and Better Auth matches routes against its configured basePath
  // (/api/auth by default), which needs that full path.
  expressApp.all('/api/auth/*splat', toNodeHandler(auth));

  // Restores body parsing for every route outside /api/auth/*, which the
  // line above never reaches (its handler ends the response itself).
  expressApp.use(express.json());

  // Swagger only covers Nest's own controllers (/, /api/*, /users,
  // /maraton). Better Auth's routes are generated dynamically and never go
  // through Nest's router, so @nestjs/swagger cannot see them; they get
  // their own reference page instead, via the openAPI() plugin in
  // auth/auth.ts (served at /api/auth/reference).
  const swaggerConfig = new DocumentBuilder()
    .setTitle('NestJS Demo API')
    .setDescription(
      'Auth (sign up, sign in, session, admin) is generated by Better Auth ' +
        'and documented separately at /api/auth/reference. This page covers ' +
        'every route Nest itself serves: /users, /maraton, the Arcjet demos ' +
        'under /api, and the root route.',
    )
    .setVersion('1.0')
    .addBearerAuth({
      type: 'http',
      scheme: 'bearer',
      description:
        'The token from sign up/sign in\'s "set-auth-token" response header.',
    })
    .build();
  const swaggerDocument = SwaggerModule.createDocument(app, swaggerConfig);
  SwaggerModule.setup('api/docs', app, swaggerDocument);

  await app.listen(process.env.PORT ?? 3000);
}
await bootstrap();
